### ISSUE TITLE
question on pre_data.py

### ISSUE THREAD

**Issue by MEIMEIMEIMEIMEMEDA** [MANLP-suda/JML#11]
Hello, when I run pre_data.py, the test and dev data can transfer to multi aspect data successfully, however, the train data is not ok, and there is a error that:

(pytorch) root@1hhh/JML-main/JML_opened/data/Twitter# python pre_data.py 
--------------IJCAI2019_data/twitter2015/test.txt---------------
--------------IJCAI2019_data/twitter2015/dev.txt---------------
--------------IJCAI2019_data/twitter2015/train.txt---------------
Traceback (most recent call last):
  File "pre_data.py", line 145, in <module>
    write_data(data_add,save_path,Image_datas)
  File "pre_data.py", line 124, in write_data
    image_info=get_img_info(id,image_datas,dataset)
  File "pre_data.py", line 112, in get_img_info
    assert da_img['sentext'] == da_raw['sentent']
AssertionError

Therefore, I want to ask if the json file in /data/Twitter/twitter15 (the file path is the file location in baiduyun) can be used in pre_data.py, if not, which one should be used in pre_data.py in line 143?

Thank you!

**Comment by MANLP-suda** [comment]
You can try the pre_data.py in folder twitter_17_pre and this code may be errorless.  Besides, you can just use the provided pre-processed data without pre_data.py.
