### ISSUE TITLE
The utils package lacks a lot of modules

### ISSUE THREAD

**Issue by schicksa** [MANLP-suda/JML#7]
if i use the follow commands:
$ bash run_joint_method_(15/17).sh

Will feedback errors, such as 
**No module named 'utils.multihead'
No module named 'utils.data_loader_bb'**

Could you please put some training code which can execute?
Thank you

**Comment by MANLP-suda** [comment]
![image](https://user-images.githubusercontent.com/69071185/158735621-7965c8a6-bc36-4a07-a044-acebf39e4c92.png)
**utils.multihead**  and **utils.data_loader_bb** are existing in  the code,  may your environment be same to the settings?
Besides, before you execute the code, the **data** and **resnet** checkpoint should be downloaded.

**Comment by schicksa** [comment]
Pardon me for being so carelessness.
I didn't notice that the **utils** module under the absa package and the **utils** package had the same name, resulting in the automatic import another one.

**Comment by 257556227** [comment]
请问大佬 **run_joint_method_(15/17).sh** 文件是不是就是[joint_method_15.sh]和joint_method_17.sh啊，可是这二者我运行后，返回结果都是空，且里面内容也都只是配置，没有说从哪个python文件开始运行啊，是我哪里弄错了吗
同理，我也没找到**joint_train.s**h 这个文件
望大佬解答

**Comment by MANLP-suda** [comment]
joint_method_15.sh 和joint_method_17.sh 里面有执行的python文件名，你看看环境正确了没，还有文件下载了没

**Comment by Enping1** [comment]
大佬你好，就如257556227所言，joint_method_15.sh确实里面仅仅是配置啊，确实没看到有执行的python文件名

**Comment by MANLP-suda** [comment]
![image](https://user-images.githubusercontent.com/69071185/172540362-3d3ab12d-f69c-4610-b015-97ae8ddf97af.png)
![image](https://user-images.githubusercontent.com/69071185/172540392-502cf3b3-b70d-42eb-80d4-10c1496d1c30.png)
这是对应的执行文件，"xxx.py"省略了

**Comment by Enping1** [comment]
大佬您好：
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 非常感谢您前面回答我的问题，我对您的论文和研究方法非常感兴趣，目前还有一些问题，很想多跟您沟通。 不知道能否加您微信呢？加了微信沟通更加方便。我的微信是：13618041167

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 目前还有一个问题： 我再重新处理数据，发现，跑twitter2015的pre_data.py 的时候 ，报错如：
Traceback (most recent call last):
&nbsp; File "/home/tiggers/Newdisk/lep/JML/JML-main/JML_opened/data/Twitter/IJCAI2019_data/twitter2015/pre_data.py", line 185, in <module&gt;
&nbsp;&nbsp;&nbsp; write_data(data_add,save_path,Image_datas)
&nbsp; File "/home/tiggers/Newdisk/lep/JML/JML-main/JML_opened/data/Twitter/IJCAI2019_data/twitter2015/pre_data.py", line 163, in write_data
&nbsp;&nbsp;&nbsp; image_info=get_img_info(id,image_datas,dataset)
&nbsp; File "/home/tiggers/Newdisk/lep/JML/JML-main/JML_opened/data/Twitter/IJCAI2019_data/twitter2015/pre_data.py", line 151, in get_img_info
&nbsp;&nbsp;&nbsp; assert da_img['sentext'] == da_raw['sentent']
&nbsp;&nbsp;&nbsp; 追溯代码发现好像是train.json文件读出的内容在这里assert不一致？这是怎么回事呢？

&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 还有，twitter2017好像没有json文件？那这个pre_data.py文件怎么处理？


非常感谢大佬！！




330953797
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MANLP-suda/JML"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月8日(星期三) 中午1:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MANLP-suda/JML] The utils package lacks a lot of modules (Issue #7)





 

 
 这是对应的执行文件，"xxx.py"省略了
